import type { Metadata } from "next";
import Link from "next/link";
import { GameplayVideo } from "@/components/GameplayVideo";
import { GuideRail } from "@/components/GuideRail";
import { JsonLd } from "@/components/JsonLd";
import { PageHero } from "@/components/PageHero";
import { videoDemos } from "@/data/site";
import farmData from "@/data/farm-data.json";
import { breadcrumbSchema, webPageSchema } from "@/lib/seo";

export const metadata: Metadata = { title: "Farm an Island Seeds, Crops and XL Plants", description: "See available Farm an Island crop details and watch fertilizer turn a Durian into an XL Durian.", alternates: { canonical: "/seeds-and-crops" } };

export default function CropsPage() { return <>
  <JsonLd data={[webPageSchema({ name: "Farm an Island Seeds, Crops and XL Plants", description: metadata.description as string, path: "/seeds-and-crops" }), breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Seeds and crops", path: "/seeds-and-crops" }])]} />
  <PageHero eyebrow="Seeds and crops" title="Start with these five crops" answer="Carrot, Tomato, Potato, Bell Pepper and Durian have useful card or task details below. Complete seed costs, growth times, yields and Bank values are not available yet." nextHref="#catalog" nextLabel="See crop details" image={{ src: "/hero-bg.jpg", alt: "Official Farm an Island artwork showing planted areas on an island" }} status="Details checked Jul 25 and Aug 5, 2026" />
  <section className="section"><div className="page-shell content-layout"><div>
    <article className="content-panel" id="loop"><span className="eyebrow">Crop loop</span><h2>Plant, harvest, then check the Bank deal</h2><p>A crop name alone is not enough to rank profit because the Bank deal can change.</p><ol className="number-list"><li>Plant a seed on an open plot.</li><li>Wait for the crop to finish growing.</li><li>Harvest it and inspect the crop card.</li><li>Check the current Bank deal before transferring the batch.</li></ol></article>
    <article className="content-panel" id="catalog"><span className="eyebrow">Crop details</span><h2>What is available for each crop</h2><table className="data-table"><thead><tr><th>Crop</th><th>Available detail</th><th>Last checked</th></tr></thead><tbody>{farmData.observedCrops.map((crop) => <tr key={crop.name}><td><strong>{crop.name}</strong></td><td>{crop.knownFields}</td><td>{crop.sourceDate}</td></tr>)}</tbody></table><p className="player-note"><strong>No profit ranking yet.</strong> Complete seed costs, growth times, yields and Bank values are still missing, so this list cannot name a best crop.</p></article>
    <article className="content-panel" id="xl"><span className="eyebrow">XL plants</span><h2>Watch fertilizer turn a Durian into XL Durian</h2><p>{farmData.xlObservation.methodShown} The card changed from Durian to {farmData.xlObservation.crop}. Its displayed amount changed from {farmData.xlObservation.beforeDisplay} to {farmData.xlObservation.afterDisplay}.</p><table className="data-table"><tbody><tr><th>Example result</th><td>{farmData.xlObservation.crop}</td></tr><tr><th>Card details</th><td>{farmData.xlObservation.rarity}, Level {farmData.xlObservation.level}, {farmData.xlObservation.state}</td></tr><tr><th>Not known yet</th><td>{farmData.xlObservation.limit}</td></tr></tbody></table><GameplayVideo actionLabel="Play the XL Durian demonstration" poster="/hero-bg.jpg" posterAlt="Farm an Island crops used as the XL Durian video cover" startAt={videoDemos.xlDurian.startAt} title="Farm an Island XL Durian demonstration" videoId={videoDemos.xlDurian.videoId} /><div className="next-card"><h3>Ready to turn crops into cash?</h3><p>The Bank guide explains how to read the changing deal before transferring a batch.</p><Link className="button button-action" href="/bank-and-money">Continue to Bank and money</Link></div></article>
  </div><GuideRail links={[{ href: "#loop", label: "Crop loop" }, { href: "#catalog", label: "Crop details" }, { href: "#xl", label: "XL Durian video" }]} nextActions={[{ href: "/bank-and-money", label: "Use the Bank", description: "Turn harvested crops into cash." }, { href: "/land-expansion", label: "Plan an expansion", description: "Compare your cash with early land costs." }]} /></div></section>
</>; }
