import type { Metadata } from "next";
import Link from "next/link";
import { GuideRail } from "@/components/GuideRail";
import { JsonLd } from "@/components/JsonLd";
import { PageHero } from "@/components/PageHero";
import { SourceNote } from "@/components/SourceNote";
import { communityReports } from "@/data/site";
import farmData from "@/data/farm-data.json";
import { breadcrumbSchema, webPageSchema } from "@/lib/seo";

export const metadata: Metadata = { title: "Farm an Island Seeds, Crops and XL Plants", description: "See crops observed in Farm an Island gameplay, their known card fields, and what the XL Durian demonstration does and does not prove.", alternates: { canonical: "/seeds-and-crops" } };

export default function CropsPage() { return <>
  <JsonLd data={[webPageSchema({ name: "Farm an Island Seeds, Crops and XL Plants", description: metadata.description as string, path: "/seeds-and-crops" }), breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Seeds and crops", path: "/seeds-and-crops" }])]} />
  <PageHero eyebrow="Seeds and crops" title="Five crops are visible in dated gameplay" answer="Carrot, Tomato, Potato, Bell Pepper, and Durian appear in the reviewed target-game footage. Their complete seed costs, growth times, yields, and Bank values are still not available as one reliable table." nextHref="#catalog" nextLabel="See observed crops" image={{ src: "/hero-bg.jpg", alt: "Official Farm an Island artwork showing planted areas on an island" }} status="Gameplay dated Jul 25 and Aug 5, 2026" />
  <section className="section"><div className="page-shell content-layout"><div>
    <article className="content-panel" id="confirmed"><span className="eyebrow">Crop loop</span><h2>Plant, harvest, then check the Bank deal</h2><p>The Roblox description connects seeds and crops to the Bank. Gameplay also shows that the Bank deal can change, so a crop name alone is not enough to rank profit.</p><ol className="number-list"><li>Plant a seed on an open plot.</li><li>Wait for the crop to finish growing.</li><li>Harvest it and inspect the crop card.</li><li>Check the current Bank deal before transferring the batch.</li></ol></article>
    <article className="content-panel" id="catalog"><span className="eyebrow">Observed crops</span><h2>What the reviewed footage actually shows</h2><table className="data-table"><thead><tr><th>Crop</th><th>Known fields</th><th>Source date</th></tr></thead><tbody>{farmData.observedCrops.map((crop) => <tr key={crop.name}><td><strong>{crop.name}</strong></td><td>{crop.knownFields}</td><td>{crop.sourceDate}</td></tr>)}</tbody></table><SourceNote tone="unknown" title="No reliable profit ranking yet">A competitor publishes approximate seed and Bank values, but the rows do not have a second same-build source. This page does not use those numbers to name a best crop.</SourceNote></article>
    <article className="content-panel" id="xl"><span className="eyebrow">XL plants</span><h2>One fertilizer demonstration produced an XL Durian</h2><p>{farmData.xlObservation.methodShown} The card changed from Durian to {farmData.xlObservation.crop}. Its displayed amount changed from {farmData.xlObservation.beforeDisplay} to {farmData.xlObservation.afterDisplay}.</p><table className="data-table"><tbody><tr><th>Observed crop</th><td>{farmData.xlObservation.crop}</td></tr><tr><th>Card fields</th><td>{farmData.xlObservation.rarity}, Level {farmData.xlObservation.level}, {farmData.xlObservation.state}</td></tr><tr><th>What remains unknown</th><td>{farmData.xlObservation.limit}</td></tr></tbody></table><SourceNote tone="reported" title={communityReports.xl.label}><a className="text-link" href={communityReports.xl.href} target="_blank" rel="noreferrer">Watch the dated demonstration</a>. {communityReports.xl.note}</SourceNote><div className="next-card"><h3>Ready to turn crops into cash?</h3><p>The Bank page explains the changing deal shown in the same beginner footage.</p><Link className="button button-action" href="/bank-and-money">Continue to Bank and money</Link></div></article>
  </div><GuideRail links={[{ href: "#confirmed", label: "Crop loop" }, { href: "#catalog", label: "Crop table status" }, { href: "#xl", label: "XL plant record" }]} /></div></section>
</>; }
